<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="2" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-04-20T12:57:40 IST" name="Default suite" finished-at="2022-04-20T12:58:13 IST" duration-ms="33067">
    <groups>
    </groups>
    <test started-at="2022-04-20T12:57:40 IST" name="Default test" finished-at="2022-04-20T12:58:13 IST" duration-ms="33067">
      <class name="com.harman.test.LoginTest">
        <test-method is-config="true" signature="setup()[pri:0, instance:com.harman.test.LoginTest@6253c26]" started-at="2022-04-20T12:57:40 IST" name="setup" finished-at="2022-04-20T12:57:51 IST" duration-ms="10834" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="invalidCredentialTest(java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:com.harman.test.LoginTest@6253c26]" started-at="2022-04-20T12:57:51 IST" name="invalidCredentialTest" data-provider="invalidCredentialData" finished-at="2022-04-20T12:57:53 IST" duration-ms="2144" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[john]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[john123]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Invalid credentials]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- invalidCredentialTest -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:com.harman.test.LoginTest@6253c26]" started-at="2022-04-20T12:57:53 IST" name="teardown" finished-at="2022-04-20T12:57:54 IST" duration-ms="587" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:com.harman.test.LoginTest@6253c26]" started-at="2022-04-20T12:57:54 IST" name="setup" finished-at="2022-04-20T12:58:01 IST" duration-ms="7104" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="invalidCredentialTest(java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:com.harman.test.LoginTest@6253c26]" started-at="2022-04-20T12:58:01 IST" name="invalidCredentialTest" data-provider="invalidCredentialData" finished-at="2022-04-20T12:58:03 IST" duration-ms="2129" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[peter]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[peter123]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Invalid credentials]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- invalidCredentialTest -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:com.harman.test.LoginTest@6253c26]" started-at="2022-04-20T12:58:03 IST" name="teardown" finished-at="2022-04-20T12:58:04 IST" duration-ms="517" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:com.harman.test.LoginTest@6253c26]" started-at="2022-04-20T12:58:04 IST" name="setup" finished-at="2022-04-20T12:58:11 IST" duration-ms="6963" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="validCredentialTest()[pri:0, instance:com.harman.test.LoginTest@6253c26]" started-at="2022-04-20T12:58:11 IST" name="validCredentialTest" finished-at="2022-04-20T12:58:13 IST" duration-ms="2070" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [https://opensource-demo.orangehrmlive.com/index.php/dashboard] but found [https://opensource-demo.orangehrmlive.com/index.php/auth/validateCredentials]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [https://opensource-demo.orangehrmlive.com/index.php/dashboard] but found [https://opensource-demo.orangehrmlive.com/index.php/auth/validateCredentials]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at com.harman.test.LoginTest.validCredentialTest(LoginTest.java:20)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validCredentialTest -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:com.harman.test.LoginTest@6253c26]" started-at="2022-04-20T12:58:13 IST" name="teardown" finished-at="2022-04-20T12:58:13 IST" duration-ms="602" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- com.harman.test.LoginTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
